# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ArchC
author: ArchC Team
email: archc@archc.org
description: > # this means to ignore newlines until "baseurl:"
  ArchC is a powerful and modern open-source architecture description language designed at University of Campinas by the ArchC team in the Computer Systems Laboratory, Institute of Computing.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://archc.org" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  ArchC

# Build settings
markdown: kramdown
